### ISSUE TITLE
Support for roles in bearer tokens

### ISSUE THREAD

**Issue by loremaps** [SectorLabs/keycloak-mock#6]
Hi,

We use [keycloak-connect](https://github.com/keycloak/keycloak-nodejs-connect) and protect routes using specific roles using the [.protect()](https://www.keycloak.org/docs/latest/securing_apps/index.html#protecting-resources) method. E.g.:

```js
router.get('/admin', keycloak.protect('admin'), function (req, res, next) { ... }));
```

AFAIK we cannot setup roles right now. So whenever we create a token with `MockInstance.createBearerToken()` we get a `403` for the example above.

In order to support this we need the bearer token to include something like:

```js
 return jwt.sign(
    {
      ...
      resource_access: { 'my-admin-client-id': { roles: ['admin'] } },
    },
    options.key.toPEM(true),
    { ... }
  );
```

An easy solution could be to accept a generic object with additional properties we wish the bearer token to have. 

Another solution could be to add support for roles with `database.createUser()`?

Would you accept a PR for the 1st solution?

**Comment by BenJeau** [comment]
I am also in the need of having `roles` supported for the keycloak mock (it would complete my testing for my application).

@loremaps I think either way is fine since its just a mock. I wonder what is the opinion of the maintainers, @Photonios?

**Comment by Kalgros20** [comment]
Hi, can you share a little example how you guys are doing your mock setup and using in tests? I'm having a little of trouble to do my setup/config with mocha. I'm algo using keycloak-connect, and i don't really don't know if my test is hitting the mock. U_U"
